### ISSUE TITLE
ScopedDependency issue after refactor to 5.1.4

### ISSUE THREAD

**Issue by Ultre00** [abpframework/abp#12206]
Current ABP version 5.1.4 (migrated from 3.3.2)
Database provider: EF Core

The issue I am facing is that I have a class similar to the ICurrentTenantAccessor that I use to set some variables in a middleware. I then later use these variable in the DbContext to apply some global filters (like the CurrentTenant does aswell). However since I upgraded to the latest 5.1.4 version the scoped dependency instance is not the same when injected in the Middleware / DbContext. So I created a minimal class to check if the issue occurs there as well and it did.

Created a class:
```c#
public class ShouldBeScoped : IScopedDependency
{
    private readonly Guid Test;

    public ShouldBeScoped()
    {
        Test = Guid.NewGuid();
    }
 }
```
Then in both the Middleware and the DbContext I added these 2 dependencies:
```c#
private readonly ShouldBeScoped _shouldBeScoped;
private readonly ICurrentTenantAccessor _currentTenantAccessor;
```
And added some debug logging in the constructors:
```c#
Debug.WriteLine($"Middleware - _currentTenantAccessor: {_currentTenantAccessor.GetHashCode()}");
Debug.WriteLine($"Middleware - _shouldBeScoped: {_shouldBeScoped.GetHashCode()}");
```
The results:
```
Middleware - _currentTenantAccessor: 49949015
Middleware - _shouldBeScoped: 44608073
AbpDbContext - _currentTenantAccessor: 49949015
AbpDbContext - _shouldBeScoped: 64184504
```
So I was wondering, am I overlooking something here? The CurrentTenantAccessor still works the way it should, but the simple class does not and I had no issues prior to the refactor.

**Comment by maliming** [comment]
hi 

Do you get services from `HttpContext.RequestServices`?

**Comment by Ultre00** [comment]
@maliming I was injecting them in the constructor. Thanks I think if I change it to the `HttpContext.RequestServices` and the reason the ICurrentTenantAccessor is working is probably because it is not a scoped instance but a singleton

**Comment by maliming** [comment]
You can try to get `ShouldBeScoped ` from `HttpContext.RequestServices`.

**Comment by Ultre00** [comment]
For some reason it still isn't working as intended:

Middleware:
```C#
Debug.WriteLine($"{context.RequestServices.GetRequiredService<ShouldBeScoped>().GetHashCode()}");
```
returns a different hashcode then the one in the DbContext

**Comment by maliming** [comment]
Can you share a simple project?

**Comment by Ultre00** [comment]
@maliming

https://github.com/Ultre00/ScopedDependencyDemo

- Created a new ABP solution
- Added a new Demo.Shared module with the simple classes
- Added DemoAppService with Demo endpoint to trigger the DbContext constructor
- Added the Debug.WriteLines to check the hashcodes

**Comment by JadynWong** [comment]
You can use `IHybridServiceScopeFactory` to resolve your scoped services.

`AbpDbContext` is resolved by the ServiceProvider in UnitOfWork, which is a separate scope.

![image](https://user-images.githubusercontent.com/13699353/162417350-a1e4d320-6a45-46fb-b3ca-820630059de2.png)

**Comment by Ultre00** [comment]
That fixed the issue, thanks!

**Comment by MannRobertJ** [comment]
I'm now facing the same issue and the `IHybridServiceScopeFactory` no longer exists. What is the new solution?

**Comment by maliming** [comment]
> IHybridServiceScopeFactory

hi

`IServiceScopeFactory`

**Comment by MannRobertJ** [comment]
Hi,

Thanks for the response. Unfortunately this doesn't solve the issue.

I've tried like 

    public MyProjectDbContext(DbContextOptions<MyProjectDbContext> options, IServiceScopeFactory scopeFactory)
        : base(options)
    {
        _shouldBeScoped = scopeFactory.CreateScope().ServiceProvider.GetRequiredService<ShouldBeScoped>();
    }

and

    public MyProjectDbContext(DbContextOptions<MyProjectDbContext> options, IServiceScopeFactory scopeFactory)
        : base(options)
    {
        using var scope = scopeFactory.CreateScope();
        _shouldBeScoped = scope.ServiceProvider.GetRequiredService<ShouldBeScoped>();
    }

In both cases it resolves a new instance of `ShouldBeScoped`. 

I see that the implemention of `IServiceScopeFactory` that gets resolved is `AutofacServiceScopeFactory`. Could it be that I need a different implementation?

Also if it makes a difference I'm using EFCore with Blazor Server.

**Comment by maliming** [comment]
hi @MannRobertJ 

Please create a new issue. Thanks.
